# Generated by Django 4.0.4 on 2022-05-29 23:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0153_created_datetimefield'),
        ('netbox_static_routes', '0002_alter_staticroute_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticroute',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='dcim.device'),
        ),
        migrations.AlterField(
            model_name='staticroute',
            name='distance',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(255)]),
        ),
        migrations.AlterField(
            model_name='staticroute',
            name='next_hop',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
